services:
  lab-6-docker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - userid=${userid}
        - groupid=${groupid}
    container_name: lab-6-container
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    image: lab-6-image:latest
    # Required for communicating over the network
    network_mode: "host"
    ipc: "host"
    pid: "host"
    # Required for accessing hardware
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ../src:/home/robot/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw